main: net.tfminecraft.woodworking.Woodworking
api-version: '1.21.10'
name: Woodworking
version: ${project.version}
author: Drefvelin

depend: [TLibs, MMOItems, MythicLib]
softdepend: [ItemsAdder]

commands:
  woodworking:
    usage: /<command> reload | select <projectId>
    description: Woodworking admin command

permissions:
  woodworking.admin:
    description: Access to Woodworking admin commands
    default: op
